### ISSUE TITLE
Question about guard in invalidateLayoutWithContext

### ISSUE THREAD

**Issue by bdpdx** [cnoon/CollectionViewAnimations#1]
In Layout.swift's `invalidateLayoutWithContext()` you have this code:

`guard invalidationContext.invalidateEverything || invalidationContext.invalidateSectionHeaders else { return }`

Did you ever see this `guard` actually get hit?  It seems somewhat out of place to be checking whether invalidation is necessary in the function responsible for doing invalidation.  Your `shouldInvalidateLayoutForBoundsChange()` just returns `true`, so it makes sense, but do you think it would be more performant (or at least logically more organized) to refactor the checks to `shouldInvalidateLayoutForBoundsChange()`?

Great work btw, I hope loads of people find this project--I'm just musing.

**Comment by cnoon** [comment]
Great catch!

That line was originally a safety check when I was figuring out how to properly use an invalidation context. I always felt that it was either not necessary, or could be cleaner. You pointing it out was just the nudge I needed to revisit that logic. I managed to rework the entire function into a much cleaner solution in 1e796198.

Thanks for the nudge! 😉
